# Frequency
FS = 7000
TS = 0.05
FREQ_NONOISE1_0 = 1297
FREQ_NONOISE1_1 = 1697
FREQ_NONOISE2_0 = 2297
FREQ_NONOISE2_1 = 2699
SAMPLES_PER_VECTOR = int(TS * FS)

# Vectors
BITS_TO_SEND = 2040
VECTORS_CHUNKS_SIZE_BEFORE_ZEROS = 102
NUMBER_VECTOR_GROUPS = int(BITS_TO_SEND / VECTORS_CHUNKS_SIZE_BEFORE_ZEROS)
NUMBER_ZEROS_INTERLEAVING = NUMBER_VECTOR_GROUPS - 1
NUMBER_SAMPLES_PER_VECTORS_CHUNK = VECTORS_CHUNKS_SIZE_BEFORE_ZEROS * SAMPLES_PER_VECTOR
NUMBER_VECTORS_TO_SEND = VECTORS_CHUNKS_SIZE_BEFORE_ZEROS * NUMBER_VECTOR_GROUPS
NUMBER_DATA_SAMPLES = NUMBER_VECTORS_TO_SEND * SAMPLES_PER_VECTOR
TIME_ZERO_INTERLEAVING = 2
NUMBER_ZEROS_SAMPLES = 2 * FS
NUMBER_ZEROS_SAMPLES_TOTAL = (NUMBER_ZEROS_INTERLEAVING) * NUMBER_ZEROS_SAMPLES

# Noise
NOISE_SEED = 42
NOISE_DURATION = 2
NUMBER_NOISE_SAMPLES = int(NOISE_DURATION * FS)

ADDITIONAL_TIME_TO_RECORD = 4
ADDITIONAL_SAMPLES_TO_RECORD = ADDITIONAL_TIME_TO_RECORD * FS
RECORDING_SAMPLES_TOTAL = NUMBER_DATA_SAMPLES + \
    NUMBER_NOISE_SAMPLES + NUMBER_ZEROS_SAMPLES_TOTAL + ADDITIONAL_SAMPLES_TO_RECORD

# MAGIC_NUMBER = 35
MAGIC_NUMBER = 0
MAGIC_THRESHOLD = 0.06
